- hosts: all
  become: true
  tasks:

    - name: Install Apache and PHP packages
      dnf:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        update_cache: yes
      when: ansible_os == "RedHat"
